// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiP6DYEehaaFPhD0kVqTR90HjqMZQIBbg',
    appId: '1:951530749279:web:3a68db0feb533b8e2d0aea',
    messagingSenderId: '951530749279',
    projectId: 'oua-bootcamp-4f876',
    authDomain: 'oua-bootcamp-4f876.firebaseapp.com',
    storageBucket: 'oua-bootcamp-4f876.appspot.com',
    measurementId: 'G-D20DRBM9Y8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-y6z2YuykBmlyv--aA3TE-38-B5rCCMs',
    appId: '1:951530749279:android:119f769c20d8a9bb2d0aea',
    messagingSenderId: '951530749279',
    projectId: 'oua-bootcamp-4f876',
    storageBucket: 'oua-bootcamp-4f876.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhWnh_gLWmit4H8mPHgcg7pJe1SdDxSS4',
    appId: '1:951530749279:ios:9e5939b8f6c87f332d0aea',
    messagingSenderId: '951530749279',
    projectId: 'oua-bootcamp-4f876',
    storageBucket: 'oua-bootcamp-4f876.appspot.com',
    iosBundleId: 'com.muirti.ouabootcamp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiP6DYEehaaFPhD0kVqTR90HjqMZQIBbg',
    appId: '1:951530749279:web:60b45110517dcc842d0aea',
    messagingSenderId: '951530749279',
    projectId: 'oua-bootcamp-4f876',
    authDomain: 'oua-bootcamp-4f876.firebaseapp.com',
    storageBucket: 'oua-bootcamp-4f876.appspot.com',
    measurementId: 'G-54QQ75R9V2',
  );
}
